apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: httpd-alpine
        image: httpd:2.4-alpine
  selector:
    matchLabels:
      app: myapp
    